services:
  kafka:
    image: apache/kafka:4.1.0
    container_name: network-monitor-kafka

    ports:
      - "9092:9092"

    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093

      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

  postgres:
    image: postgres:17
    container_name: network-monitor-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: network_monitor
      POSTGRES_USER: network_monitor
      POSTGRES_PASSWORD: network_monitor_dev
    ports:
      - "5434:5432"
    volumes:
      - network-monitor-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U network_monitor -d network_monitor"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  network-monitor-postgres-data:
    